
spring:
  datasource:
    name: zerg
    url: jdbc:mysql://******:3306/zerg?characterEncoding=UTF-8
    username: root
    password: ******
    drive-class-name: com.mysql.cj.jdbc.Driver
#server:
#  port: 8081
