
spring:
  datasource:
    name: zerg
    url: jdbc:mysql://47.99.218.29:3306/zerg?characterEncoding=UTF-8
    username: root
    password: Gqk_0725
    drive-class-name: com.mysql.cj.jdbc.Driver
#server:
#  port: 8081
